spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

auth:
  jwt:
    secret: ${JWT_SECRET}
    header: ${JWT_HEADER}
    prefix: ${JWT_PREFIX}
    exp:
      access: ${JWT_ACCESS}
      refresh: ${JWT_REFRESH}