name: CI

# 모든 브랜치에서 Push가 일어났을 때
on:
  workflow_dispatch:
  push:

jobs:
  build:
    # 작업 실행 환경 ubuntu로 변경
    runs-on: ubuntu-latest

    # 환경 변수 지정
    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
    # 저장소 체크아웃
      - uses: actions/checkout@v4

      # JDK 17 설정
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Gradle Build
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # Gradle Test
      - name: Run test with Gradle
        run: ./gradlew test
